### ISSUE TITLE
WPS317: non deterministic behaviors on different parameters

### ISSUE THREAD

**Issue by cyyc1** [wemake-services/wemake-python-styleguide#2504] opened 2022-09-30 07:26 UTC
### What's wrong

Here's a test case to reproduce this bug:

```python
"""This is some docstring."""

aa = [
    (1, (2, 3), 'a'),
    (2, (3, 4), 'b'),
]

bb = [
    (1, (2, 3), 1, 'a'),
    (2, (3, 4), 2, 'b'),
]

cc = [
    (1, 2, (2, 3), 1, 'a'),
    (2, 3, (3, 4), 2, 'b'),
]

```

Copying and pasting the code above to the online playground (https://wps.orsinium.dev/), and I got the following error

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/114281716/193214508-19c7a9eb-4108-4e66-a2d5-5d95ad50db0e.png">

### How it should be

I don't think WPS317 should be thrown for `bb` and `cc`, because `bb` and `cc` appear to follow the WPS317 style recommendation.

At the very least the behavior for `aa`, `bb`, and `cc` should be consistent: either they all show WPS317 violation, or non of them does.

### Flake8 version and plugins

I used the playground. So I suppose I'm using WPS 0.17.0.

### pip information

N/A. I was using the playground.

### OS information

N/A. I was using the playground.

**Comment by sobolevn** [comment] 2022-09-30 07:28
DUplicate of https://github.com/wemake-services/wemake-python-styleguide/issues/454

**Closed by sobolevn** 2022-09-30 07:28 UTC
Labels: bug
