### ISSUE TITLE
WPS323 Found `%` string formatting for datetime.strftime('%d.%m.%Y')

### ISSUE THREAD

**Issue by tahirjalilov** [wemake-services/wemake-python-styleguide#1796] opened 2020-12-26 08:22 UTC
# Bug report

## What's wrong

linter show me the warning WPS323 Found `%` string formatting when I use date/time formatting like  datetime.strftime('%d.%m.%Y')

## How it should be

Should not show the warning

**Comment by sobolevn** [comment] 2020-12-26 08:37
Thanks!

But it is a duplicate of #1329

**Closed by sobolevn** 2020-12-26 08:37 UTC
Labels: bug
