### ISSUE TITLE
WPS323 False positive

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1489] opened 2020-06-29 17:42 UTC
## What's wrong

```
seen.strftime("%a %b %d :%M")
```

where seen is a datetime.datetime object.

## How is that should be

The characters are datetime's formatting parameters, not general % string formatting. This shouldn't cause a violation.

**Comment by sobolevn** [comment] 2020-06-29 18:01
Duplicate of #1329

**Closed by sobolevn** 2020-06-29 18:01 UTC
Labels: bug
