### ISSUE TITLE
Warn about invalid string type for docstring

### ISSUE THREAD

**Issue by orsinium** [wemake-services/wemake-python-styleguide#1603] opened 2020-09-14 12:07 UTC
# Rule request

## Thesis

F-strings and bytes cannot be used as a docstring (raw strings is ok). For example:

```python
def ab(a, b):
  f"""oh hi
  """
  return a+b
```

In the example above, neither `inspect.getdoc` nor `ast.get_docstring` will interpret the f-string as a docstring.

Also, `get_docstring` is a good reference for the check implementation: https://github.com/python/cpython/blob/3.8/Lib/ast.py#L236-L259

## Reasoning

It's a bug. Once I tried to use an f-string-based docstring to reuse something inside because we use docstrings to generate OpenAPI spec. Turned out it doesn't work.

**Comment by sobolevn** [comment] 2020-09-14 13:12
This is a duplicate of https://github.com/PyCQA/pydocstyle/pull/381

**Closed by sobolevn** 2020-09-14 13:12 UTC
Labels: rule request
