### ISSUE TITLE
flake8 failed 

### ISSUE THREAD

**Issue by nikiforniko** [wemake-services/wemake-python-styleguide#1510] opened 2020-07-16 18:31 UTC
# Bug report

## What's wrong
Hello! I just started my new project with poetry and immediately installed WPS with "poetry add wemake-python-styleguide"
After success installation, I tried running flake8, and i got a Traceback

```
Traceback (most recent call last):
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 328, in initialize
    self.find_plugins(config_finder)
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/main/application.py", line 159, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/plugins/manager.py", line 415, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/plugins/manager.py", line 413, in load_plugin
    return plugin.load_plugin()
  File "/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/flake8/plugins/manager.py", line 164, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "I00" due to cannot import name 'SortImports' from 'isort' (/home/nderyushev/.cache/pypoetry/virtualenvs/hrd-RA6JvueO-py3.8/lib/python3.8/site-packages/isort/__init__.py).
```

## How is that should be

I found out that this is due to the update of package versions of "isort" and "flake8-isort"
Maybe you have dependency problems with this packages?
So, how can I run flake8 with WPS?
Thanks

**Comment by sobolevn** [comment] 2020-07-16 19:23
Duplicate of #1503 

Currently you have to downgrade your `isort` to `<5`.
I will release a fix soon, please stay tuned.

**Closed by sobolevn** 2020-07-16 19:23 UTC
Labels: bug
